[toolchain]

[features]
seeds = false
skip-lint = false

[programs.devnet]
presale_contract = "DdMxyt8aCdufZgnZXcjRNzoy3VaNQmVRn7ioxCdwMuZf"


[registry]
url = "https://api.mainnet-beta.solana.com"

[provider]
cluster = "mainnet"
wallet = "/home/zeroex/.config/solana/Deployer.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
buy = "yarn run ts-node scripts/buy.ts"
init-vault = "yarn run ts-node scripts/init_vault.ts"
private-key = "yarn run ts-node scripts/private_key.ts"
