[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
presale_contract = "A4DjbJ7AVgKCcWAZpFZPUmVQvgcAEcJwGtrxGrhEHZYP"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/rss/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
buy = "yarn run ts-node scripts/buy.ts"
initVault = "yarn run ts-node scripts/initVault.ts"
privateKey = "yarn run ts-node scripts/privateKey.ts"